### ISSUE TITLE
Loggnivå vises ikke korrekt i GCP

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-baseregistries-publisher#4]
Alt tolkes som error.

Som standard tolker GCP python-logging veldig enkelt; stdout = info, stderr = error.
For å få riktig nivå, anbefales det å formatere loggene som JSON

![image](https://user-images.githubusercontent.com/8625716/108711696-05162600-7516-11eb-92bc-0a7002a8987d.png)

**Comment by stigbd** [comment]
Lukker i forbindelse med arkivering.
